---
  - name: Set hostname
    hostname:
      name: "{{ hostname }}"

  - name: Update host file
    blockinfile:
      path: /etc/hosts
      marker: "##<!-- {mark} ANSIBLE MANAGED -->"
      block: |
        127.0.1.1	{{ hostname }}

  - name: Install common packages
    apt:
      name: "{{ item.value.pkg }}"
      state: "{{ item.value.ver }}"
      update_cache: yes
    with_dict: "{{ packages }}"

  - name: Set keyboard layout
    blockinfile:
      path: /etc/default/keybaord
      marker: "##<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: |
        XKBLAYOUT=\"us\"
      create: yes

#ntp sux on the pi, this is what i had to do:
  - name: Set timezone to US/Central
    timezone:
      name: US/Central

  - name: set timezone again
    template:
      src: roles/common/templates/timezone.j2
      dest: /etc/timezone

  - name: force set timezone to save
    command: bash -c "dpkg-reconfigure -f noninteractive tzdata"
    become: yes
    notify:
    - restart ntp